task:
  name: Static Analysis
  container:
    image: python:latest
  python_modules_cache:
    folder: /usr/local/lib/python3.8/site-packages
    fingerprint_script:
      - echo $OS $PYTHON_VERSION
      - cat requirements.txt
    populate_script: python3 -m pip install --upgrade -r requirements.txt
  install_dependencies_script: |
    python3 -m pip install --upgrade pip
    python3 -m pip install --upgrade -r requirements.txt
  script: python3 -m mypy -m main
